name: Daily Commit

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-contributions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Make a Commit
        env:
          TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo "$(date): Automated commit" >> log.txt
          git config --global user.name "aelnimah"
          git config --global user.email "your-email@example.com"
          git add log.txt
          git commit -m "Automated commit"
          git push
